//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMsg
    {
        public int cid { get; set; }
        public int ToUserId { get; set; }
        public string ToRealName { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public string FromRealName { get; set; }
        public string MessageBody { get; set; }
        public System.DateTime SendTime { get; set; }
    }
}
